navigation_prompter:
  type: qwen
  client_config:
    model_name: Qwen/Qwen3-1.7B
    model_path: $SCENE_GRAPH_ASSETS/models/llm/qwen3-1.7b
    dtype: bfloat16
    use_cuda: true
    max_new_tokens: 256
    do_sample: false
    repetition_penalty: 1.0
  use_cuda: true
  clip_model:
    type: open_clip
    model_name: ViT-B-32  # ViT-L/14, ViT-B/32
    tokenizer_name: ViT-B-32
    pretrained: $SCENE_GRAPH_ASSETS/models/vlm_embedding_encoder/openclip/laion-clip-vit-b-32-s34b-b79k.safetensors
