vlm_reasoning:
  use_server: false #true if vlm is ran on remote server, false if vlm is ran locally
  vlm:
    type: cosmos_reason2
    model_name: nvidia/Cosmos-Reason2-2B
    model_path: $SCENE_GRAPH_ASSETS/models/vlm/cosmos-reason2-2b
    processor_path: ""
    dtype: bfloat16
    image_grid_thw: [1, 28, 28]
    max_new_tokens: 128
    do_sample: false
    num_beams: 1
    repetition_penalty: 1.0
  vlm_client_config:
    base_url: YOUR_SERVER_URL_HERE
    timeout: 3600
    wait_interval: 0.5
    submit_endpoint: generate
    result_endpoint: result
    verify_ssl: true
    logging: true
  use_llm_response_parser: false
  verbose: true
  include_bbs: true
find_paths_method: dijkstra
mode: one_by_one
